repos:
- repo: https://github.com/kynan/nbstripout
  rev: master
  hooks:
    - id: nbstripout
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.4.0
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
